config/routes.rb
Campus::Application.routes.draw do

  get  'new/:key' => 'topics#new'
  post 'new/:key' => 'topics#create'

  get 'member/:username' => 'users#show'
  devise_for :users

  resources :topics do
    resources :comments
  end

  resources :nodes do
    resources :topics
  end

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user
  belongs_to :topic

  validates :content, :user_id, :topic_id, :presence => true

  after_create :update_parent_topic

  def update_parent_topic
    topic.update_last_comment(self)
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :name, :key, :description, :avatar

  has_many :topics

  validates :name, :key, :presence => true
  validates :key, :uniqueness => { case_sensitive: false }
  validates :key, :format => { with: /^[a-z0-9]+$/ }

  def update_topics_count
    self.topics_count += 1
    self.save
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :content

  belongs_to :user
  belongs_to :node

  has_many :comments

  validates :title, :user_id, :node_id, :presence => true

  after_create :update_parent_node

  def update_parent_node
    node.update_topics_count
  end

  def update_last_comment(comment)
    self.last_replied_at = comment.created_at
    self.last_replied_by = comment.user.username
    self.comments_count += 1
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :username, :email, :password, :remember_me

  has_many :topics, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates :username, :presence => true
  validates :username, :uniqueness => { case_sensitive: false }
  validates :username, :length => { :maximum => 12 }
  validates :username, :format => { with: /^[a-z0-9]+$/ }

  def email=(val)
    self.email_md5 = Digest::MD5.hexdigest(val || "")
    self[:email] = val
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_topic

  def create
    @comment = @topic.comments.build(params[:comment])
    @comment.user = current_user
    if @comment.save
      redirect_to @topic, notice: 'Comment was successfully created.'
    else
      redirect_to @topic, alert: 'Fail to save comment'
    end
  end

  def destroy
    @comment = @topic.comments.find(params[:id])
    authorize! :destroy, @comment
    if @comment.destroy
      redirect_to @topic, notice: 'Comment was successfully destroyed.'
    end
  end

  protected
  def find_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base
  actions :all, :except => [:edit, :update]

  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_node, :only => [:create]
  before_filter :find_node_by_key, :only => [:new]

  def new
    if @node
      @topic = @node.topics.new
    else
      redirect_to root_url, alert: 'No such node.'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments
    @comment = @topic.comments.new
  end

  def create
    @topic = current_user.topics.build(params[:topic])
    @topic.node = @node
    if @topic.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize! :destroy, @topic
    if @topic.destroy
      redirect_to topics_url, notice: 'Topic was successfully destroyed.'
    end
  end

  protected
  def find_node_by_key
    @node = Node.find_by_key(params[:key])
  end

  def find_node
    @node = Node.find(params[:node_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if @user = User.find_by_username(params[:username])
      @topics = @user.topics
      @comments = @user.comments
    else
      redirect_to root_url, notice: 'No such user.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_avatar_width_for_size(size)
    case size
    when :normal then 48
    when :small then 16
    when :large then 64
    when :big then 120
    else size
    end
  end

  def user_avatar_tag(user, size = :normal, opts = {})
    width = user_avatar_width_for_size(size)
    avatar_img = "https://secure.gravatar.com/avatar/#{user.email_md5}?s=#{width}"
    image_tag(avatar_img, alt: user.username, class: 'avatar')
  end
end

app/views/comments/_comment.html.slim
.comment
  p= comment.content
  - if can? :destroy, comment
    - unless comment.id.nil?
      p= link_to 'Delete Comment', topic_comment_path(@topic, comment),
        method: :delete, data: { confirm: 'Are you sure?' } 

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/_header.html.slim
header.navbar.naavar_inverse
  .navbar-inner
    .container
      = link_to "Campus", '/', id: 'logo'
      nav
        ul.nav.pull-right
          - if user_signed_in?
            li = link_to 'Settings', edit_user_registration_path
            li = link_to 'Logout',   destroy_user_session_path, method: :delete
          - else
            li = link_to 'Sign up',  new_user_registration_path
            li = link_to 'Login',    new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Campus
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if lt IE 9]
      script src='http://html5shim.googlecode.com/svn/trunk/html5.js'
  body
    = render 'layouts/header'
    .container
      - if notice
        p.alert.alert-success= notice
      - if alert
        p.alert.alert-error= alert
      .span9
        = yield

app/views/topics/_comment_form.html.slim
- if user_signed_in?
  = simple_form_for [@topic, @comment] do |f|
    = f.input :content
    = f.button :submit

app/views/topics/_topic.html.slim
.topic
  .topic_title
    p= link_to topic.title, topic
  .topic_meta
    span= topic.user.username
    span= topic.last_replied_by
    span= time_ago_in_words(topic.last_replied_at) unless topic.last_replied_at.blank?

app/views/topics/index.html.slim
#topics_index
  = render @topics

app/views/topics/new.html.slim
= simple_form_for [@node, @topic] do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/topics/show.html.slim
h1= @topic.title
p= link_to @topic.user.username, user_registration_path(@topic.user)
p= @topic.content
- if can? :destroy, @topic
  p= link_to 'Delete', @topic, method: :delete, class: 'btn', data: { confirm: 'Are you sure?' }
.comments_index= render @comments if @comments.any?
=render :partial => "comment_form"

app/views/users/show.html.slim
= user_avatar_tag(@user) unless @user.nil?
.topics_index
  = render @topics
.comments_index
  / = render @comments